# Generated by Django 5.1.6 on 2025-03-01 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='The phone number of the customer.', max_length=15, verbose_name='Phone Number')),
                ('code', models.CharField(help_text='A unique code identifying the customer.', max_length=100, verbose_name='Customer Code')),
                ('user', models.OneToOneField(help_text='The user associated with this customer.', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='api.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='The total price of the order.', max_digits=10, verbose_name='Total Price')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='The quantity of the product in the order.', verbose_name='Quantity')),
                ('customer', models.ForeignKey(blank=True, help_text='The customer who placed the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.customer', verbose_name='Customer')),
                ('product', models.ForeignKey(blank=True, help_text='The product in the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(help_text='Priority for the percentage (lower values have higher priority).', verbose_name='Priority')),
                ('percentage_value', models.DecimalField(decimal_places=2, help_text='The percentage value associated with the supplier and market.', max_digits=5, verbose_name='Percentage Value')),
                ('market', models.ForeignKey(blank=True, help_text='The market associated with this percentage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percentage_markets', to='api.market', verbose_name='Market')),
                ('supplier', models.ForeignKey(blank=True, help_text='The supplier associated with this percentage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='percentage_suppliers', to='api.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Percentage',
                'verbose_name_plural': 'Percentages',
                'ordering': ['priority'],
                'unique_together': {('market', 'supplier')},
            },
        ),
    ]
