# Generated by Django 5.1.6 on 2025-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_order_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_at',
            field=models.DateField(auto_now=True, help_text='The date the order was created.', verbose_name='Creation Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The price of the order.', max_digits=10, verbose_name='Price'),
        ),
    ]
